<?php

/**
 * Implements hook_menu().
 */
function undoer_menu() {
  return array(
    'test' => array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('undoer_form'),
      'access arguments' => array('access content'),
    ),
    'do_magic' => array(
      'page callback' => 'undoer_do_magic',
      'access arguments' => array('access content'),
    ),
    'magic_wand/%' => array(
      'page callback' => 'undoer_magic_wand',
      'page arguments' => array('1'),
      'access arguments' => array('access content'),
    )
  );
}

function undoer_magic_wand($item_id) {

  $queue = DrupalQueue::get('undoer_queue', TRUE);
  $queue->deleteItem($item_id);

}

function undoer_do_magic() {
  $form = unserialize($_POST['form']);
  $form_state = unserialize($_POST['form_state']);
  $form['#submit'] = $form_state['submit_stack'];
  form_execute_handlers('submit', $form, $form_state);
}

/**
 * Implements hook_form().
 */
function undoer_form() {
  $form = array();
  $form['data'] = array(
    '#type' => 'select',
    '#options' => array('Val 1', 'Val 2'),
    '#default_value' => 0,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Test',
  );
  return $form;
}

/**
 * Form submit callback.
 *
 * See @undoer_form
 */
function undoer_form_submit($form, $form_state) {
  drupal_set_message(print_r($form_state['values'], 1), 'status', TRUE);
  watchdog('executed in', $form_state['values']['data']);
}

/**
 * Implements hook_form_alter().
 */
function undoer_form_alter(&$form, &$form_state, $form_id) {
  $form_state['submit_stack'] = $form['#submit'];
  $form['#submit'] = array('undoer_extra_callback');
}

function undoer_extra_callback($form, $form_state) {
  $data_form = serialize($form);
  $data_form_state = serialize($form_state);
//  form_execute_handlers('submit', $form, $form_state);

  $queue = DrupalQueue::get('undoer_queue', TRUE);
  $item = array(
    'timestamp' => time(),
    'form' => $data_form,
    'form_state' => $data_form_state
  );
  $queue->createItem($item);
//  drupal_http_request(url('do_magic', array('absolute' => TRUE)), array('method' => 'POST', 'data' => 'form='.$data_form.'&form_state='.$data_form_state, 'headers' => array('Content-Type' => 'application/x-www-form-urlencoded')));
}

/**
 * Implements hook_advanced_queue_info().
 */
function undoer_advanced_queue_info() {
  $items['undoer_queue'] = array(
    'label' => t('Undoer queue'),
    'worker callback' => 'undoer_queue_worker',
    // The number of seconds to retry after.
    'retry after' => 10,
    // The maximum number of attempts after a failure.
    'max attempts' => 5,
  );
  return $items;
}

function undoer_queue_worker($item, $end_time = FALSE) {
  $data = $item->data;

  $form = unserialize($item->data['form']);
  $form_state = unserialize($item->data['form_state']);
  $form['#submit'] = $form_state['submit_stack'];
  form_execute_handlers('submit', $form, $form_state);

  $queue = DrupalQueue::get('undoer_queue', TRUE);
  $queue->releaseItem($item);

  return array(
    'status' => ADVANCEDQUEUE_STATUS_SUCCESS,
    'result' => 'Processed ' . $item->item_id,
  );
}
